import "./our-js/common.js"
import "./our-js/header-modal.js"
import "./our-js/header.js";
import "./our-js/born-year.js";
import "./our-js/guss-number.js";
import "./our-js/rock-paper-scissors.js";
import "./our-js/calculator.js";
import "./our-js/time-calculator.js";
import "./our-js/dinosaur-google.js"; 
import "./our-js/football.js";
import "./our-js/max-number.js";
import "./our-js/team.js";
import "./our-js/scientists.js";
import "./our-js/space.js";
import "./our-js/footer.js";